# Workaround for https://github.com/travis-ci/travis-ci/issues/4629
before_install:
      - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

language: java
jdk:
  - oraclejdk8
